# Generated by Django 4.1.3 on 2023-01-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_movie_movie_rdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=50)),
                ('club_address', models.CharField(max_length=64)),
                ('club_city', models.CharField(max_length=64)),
                ('club_postcode', models.CharField(max_length=12)),
                ('club_phonenumber', models.CharField(max_length=100)),
                ('club_email', models.CharField(max_length=64)),
                ('rep_firstname', models.CharField(max_length=50)),
                ('rep_lastname', models.CharField(max_length=50)),
                ('rep_dateofbirth', models.CharField(max_length=50)),
            ],
        ),
    ]
