# Generated by Django 4.1.3 on 2023-01-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_club_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='user',
        ),
    ]
