# Generated by Django 4.1.5 on 2023-01-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_cinemamanagerregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemamanagerregister',
            name='role',
            field=models.CharField(default='cinema_manager', max_length=30),
        ),
    ]
