# Generated by Django 4.1.5 on 2023-01-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_cinemamanagerregister_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemamanagerregister',
            old_name='username',
            new_name='user',
        ),
    ]
