# Generated by Django 4.1.5 on 2023-01-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_first_name_cinemamanagerregister_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemamanagerregister',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='cinemamanagerregister',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
