# Generated by Django 4.1.5 on 2023-01-13 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_firstname_cinemamanagerregister_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
