# Generated by Django 4.1.5 on 2023-01-13 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_club_uuid_club_booking_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='booking_no',
            field=models.CharField(default=uuid.UUID('39cc1732-6196-4250-bdc8-c0ac62b9e839'), editable=False, max_length=50),
        ),
    ]
