# Generated by Django 4.1.5 on 2023-01-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_club_booking_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='booking_no',
            field=models.CharField(default=37060858861683050516113540504717039360, editable=False, max_length=5),
        ),
    ]
