# Generated by Django 4.1.5 on 2023-01-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_club_booking_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='booking_no',
            field=models.CharField(default=146083699940363129300761061946553752707, editable=False, max_length=5),
        ),
    ]
